
import { 
  LayoutDashboard, 
  CircleDollarSign, 
  CreditCard, 
  Users, 
  Settings, 
  ChevronRight, 
  ChevronLeft, 
  Calendar, 
  Lock, 
  Unlock, 
  Trash2, 
  Edit, 
  Plus, 
  ArrowRightLeft, 
  TriangleAlert, 
  ArrowLeft,
  ChartBar,
  Gift, 
  RotateCcw, 
  BadgeDollarSign,
  GraduationCap,
  UserRound,
  ShieldCheck,
  Crown,
  X,
  Search,
  Check,
  Square,
  ClipboardList,
  List,
  ListOrdered,
  CheckSquare,
  Type,
  Baseline,
  ChevronDown,
  ArrowRight,
  Palette,
  HandCoins,
  Wallet,
  Send,
  User,
  History,
  Star,
  TrendingUp,
  Clock,
  Database,
  Activity,
  FileText,
  Layers,
  CheckCircle2
} from 'lucide-react';

export const ICONS: Record<string, any> = {
  Dashboard: LayoutDashboard,
  Income: CircleDollarSign,
  Operations: CreditCard,
  Reports: Users,
  Users: Users,
  Models: UserRound,
  Owner: Crown,
  Settings: Settings,
  ChevronRight: ChevronRight,
  ChevronLeft: ChevronLeft,
  Calendar: Calendar,
  Lock: Lock,
  Unlock: Unlock,
  Trash: Trash2,
  Edit: Edit,
  Plus: Plus,
  Transfer: ArrowRightLeft,
  Penalty: TriangleAlert,
  AlertTriangle: TriangleAlert,
  ArrowLeft: ArrowLeft,
  Chart: ChartBar,
  Bonus: Gift,
  Gift: Gift,
  Refund: RotateCcw,
  RotateCcw: RotateCcw,
  Salary: BadgeDollarSign,
  BadgeDollarSign: BadgeDollarSign,
  ShieldCheck: ShieldCheck,
  CircleDollarSign: CircleDollarSign,
  Internship: GraduationCap,
  Crown: Crown,
  Close: X,
  Search: Search,
  ClipboardList: ClipboardList,
  Check: Check,
  List: List,
  ListOrdered: ListOrdered,
  CheckSquare: CheckSquare,
  Type: Type,
  Baseline: Baseline,
  ChevronDown: ChevronDown,
  ArrowRight: ArrowRight,
  Palette: Palette,
  HandCoins: HandCoins,
  Wallet: Wallet,
  Send: Send,
  User: User,
  History: History,
  Empty: ClipboardList,
  Star: Star,
  Clock: Clock,
  Database: Database,
  Activity: Activity,
  FileText: FileText,
  Layers: Layers,
  CheckCircle: CheckCircle2
};

export const PLATFORM_NAMES: Record<string, string> = {
  onlyFans: 'OnlyFans',
  paypal: 'PayPal',
  crypto: 'Crypto'
};

export const OPERATION_META: Record<string, { label: string; icon: any; color: string }> = {
  advance: { label: 'Аванс', icon: CircleDollarSign, color: 'text-amber-500' },
  penalty: { label: 'Штраф', icon: TriangleAlert, color: 'text-rose-500' },
  bonus: { label: 'Бонус', icon: Gift, color: 'text-emerald-500' },
  refund: { label: 'Возврат', icon: RotateCcw, color: 'text-blue-500' },
  salary_payment: { label: 'Выплата ЗП', icon: BadgeDollarSign, color: 'text-indigo-500' },
  internship: { label: 'Стажировочные', icon: GraduationCap, color: 'text-sky-400' }
};
